### ISSUE TITLE
Loading workers fails in production

### ISSUE THREAD

**Issue by koops** [codykrieger/ace-rails-ap#12]
My file looks like this:

```
#= require ace/ace
#= require ace/worker-json
#= require ace/worker-coffee
#= require ace/worker-javascript
#= require ace/mode-json
#= require ace/mode-coffee
#= require ace/mode-javascript
#= require ace/mode-markdown
#= require ace/theme-tomorrow
#= require ace/ext-searchbox
```

And everything is loading correctly in production except for the workers. It works fine in development. What am I doing wrong?

**Comment by doitian** [comment]
Here is my workaround.

First configure used workers in a const and add them to precompile list.

	# config/initializers/assets.rb
	# List used workers here
	ACE_WORKERS = %w(json) 
	Rails.application.config.assets.precompile += ACE_WORKERS.map {|w| "ace/worker-#{w}.js"}

Create a file `fix_ace_workers.js.erb` in `app/assets/javascripts/fix_ace_workers.js.erb`

	$(function() {
	  <% ACE_WORKERS.each do |w| %>
	    ace.config.setModuleUrl('ace/mode/<%= w %>_worker', <%= asset_path("ace/worker-#{w}").inspect %>);
	  <% end %>
	});

Require it after ace, do not require wokers, since they are loaded using AJAX

	// application.js
	//= require ace/ace
	//= require ace/mode-json
	//= require fix_ace_workers

**Comment by hale** [comment]
I think the basic idea is however you load the main Ace files (gem, CDN...), the workers *have* to be served from your app because of Cross-Origin policies (the worker file is loaded as a webworker with an AJAX request from the main ace.js file, I believe).

This is explained on the Ace wiki: https://github.com/ajaxorg/ace/wiki/Syntax-validation

----

To fix this I removed the gem and made the following changes:

Because in production the scripts are compiled, I needed to ensure sprockets created a separate `worker-json` file accessible at `/assets/ace/worker-json.js` in production and set the worker using `ace.config.set('workerPath', /assets/ace/)`.

**vendor**
`````
vendor
├── assets
│   ├── javascripts
│   │   └── ace
│   │       ├── ace.js
│   │       ├── mode-json.js
│   │       ├── theme-chrome.js
│   │       └── worker-json.js
│   └── stylesheets
└── plugins

5 directories, 4 files
```
**assets/ace**
```
assets/ace
├── worker-json-0afc60b3784308f9c5e265156d86b15e.js
├── worker-json-0afc60b3784308f9c5e265156d86b15e.js.gz
├── worker-json.js
└── worker-json.js.gz

0 directories, 4 files
`````

**application.js**
```
 //= require ace/ace
 //= require ace/mode-json
 //= require ace/theme-chrome
```

**application.rb**
```
 config.assets.precompile += [
        'ace/worker-json.js'
    ]
```

**Comment by randoum** [comment]
If you guys can try my PR #16 and tell us if it fixes the problem in production, would be great

**Comment by codykrieger** [comment]
Multiple reports confirm that #16 fixes this. Closing.
